services:
  webhook-api:
    build: .
    container_name: webhook-server
    restart: always
    ports:
      - "127.0.0.1:${PORT}:8080"
    stop_grace_period: 30s
    environment:
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}